Code refactoring

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,103 +1,60 @@
-# This is a basic workflow to help you get started with Actions
-
-name: CI/CD GreenCity
-# Controls when the action will run.
-
-concurrency: Testing
+name: SonarQube
 
 on:
-  # Triggers the workflow on push or pull request events but only for the master branch
   push:
-    branches: [ master, dev ]
+    branches:
+      - dev_java21
   pull_request:
-    branches: [ master, dev ]
+    types: [opened, synchronize, reopened]
 
-env:
-  repository: greencity
-  userRepoName: core
-  onbootJarName: app.jar
-  dockerRepoName: skyere/greencity
-
-  # Allows you to run this workflow manually from the Actions tab
-  workflow_dispatch:
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
   build:
+    name: Build and analyze
     runs-on: ubuntu-latest
-    # Steps represent a sequence of tasks that will be executed as part of the job
+
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Set up JDK 21
-        uses: actions/setup-java@v1
+        uses: actions/setup-java@v4
         with:
           java-version: 21
+          distribution: 'zulu'
 
-      #       - name: Set up Go
-      #         uses: actions/setup-go@v3
-      #         with:
-      #           go-version: 1.18
+      - name: Cache SonarQube packages
+        uses: actions/cache@v4
+        with:
+          path: ~/.sonar/cache
+          key: ${{ runner.os }}-sonar
+          restore-keys: ${{ runner.os }}-sonar
 
-      - name: Run a multi-line script
+      - name: Cache Maven packages
+        uses: actions/cache@v4
+        with:
+          path: ~/.m2
+          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
+          restore-keys: ${{ runner.os }}-m2
+      - name: Format code
+        run: mvn formatter:format
+
+      - name: Build and analyze
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: |
-          git fetch --unshallow
-          mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ita-social-projects-green-city -Dsonar.organization=ita-social-projects -Dsonar.host.url=https://sonarcloud.io -Dsonar.binaries=target/classes -Dsonar.dynamicAnalysis=reuseReports
+            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=GreenCity-UA-1352-02_GreenCityMVP21
 
-      - name: Test Reporter
-        uses: dorny/test-reporter@v1.5.0
-        if: success() || failure()
+      #- name: Publish JUnit Test Report
+       # uses: dorny/test-reporter@v1.5.0
+      #  if: success() || failure()
+     #   with:
+      #    name: JUnit Tests
+     #     path: '**/target/surefire-reports/*.xml'
+      #    reporter: java-junit
+
+      - name: Upload test report artifact
+        if: always()
+        uses: actions/upload-artifact@v4
         with:
-          name: Tests Report
-          path: ${{ env.userRepoName }}/target/surefire-reports/*.xml
-          reporter: java-junit
-
-      - name: Rename user jar to app
-        run: mv $userRepoName/target/*.jar $userRepoName/target/$onbootJarName
-
-      - name: Set outputs
-        run: echo "GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
-
-      - name: Docker Login
-        uses: docker/login-action@v2.0.0
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Build and push Docker images
-        uses: docker/build-push-action@v3.0.0
-        with:
-          context: .
-          file: Dockerfile
-          push: true
-          tags: ${{ env.dockerRepoName }}:test-${{ env.GITHUB_SHA_SHORT }}
-
-      #       - name: Kubernetes Set Context
-      #         uses: Azure/k8s-set-context@v3.0
-      #         with:
-      #           kubeconfig: ${{ secrets.KUBE_CONFIG }}
-      
-      #       - name: Set up Postgres
-      #         run: kubectl scale deploy postgres --replicas=1 -n test
-      
-      #       - name: Kubernetes tests
-      #         run: |
-      #           cd chart-test
-      #           go test -v ./...
-      
-      #       - name: Post Set up Postgres
-      #         if: success() || failure()
-      #         run: kubectl scale deploy postgres --replicas=0 -n test
-
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - name: Deploy 🚀
-        if: ${{ github.event_name == 'push' }}
-        uses: JamesIves/github-pages-deploy-action@3.7.1
-        with:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          BRANCH: gh-pages
-          FOLDER: .
-          CLEAN: true 
+          name: junit-test-report
+          path: '**/target/surefire-reports/*.xml'
